# Generated by Django 5.2.4 on 2025-08-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_application_cs_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
