/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatteryDeviceInfo: typeof import('./src/components/BatteryDeviceInfo.vue')['default']
    Blank: typeof import('./src/layouts/blank.vue')['default']
    ChartsGrid: typeof import('./src/components/ChartsGrid.vue')['default']
    ConnectionStatus: typeof import('./src/components/ConnectionStatus.vue')['default']
    CurrentDeviceInfo: typeof import('./src/components/CurrentDeviceInfo.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    DeviceInfo: typeof import('./src/components/DeviceInfo.vue')['default']
    DualAxisBatteryChart: typeof import('./src/components/DualAxisBatteryChart.vue')['default']
    GatewaysTable: typeof import('./src/components/tables/GatewaysTable.vue')['default']
    IonAvatar: typeof import('@ionic/vue')['IonAvatar']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardSubtitle: typeof import('@ionic/vue')['IonCardSubtitle']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonChip: typeof import('@ionic/vue')['IonChip']
    IonCol: typeof import('@ionic/vue')['IonCol']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonGrid: typeof import('@ionic/vue')['IonGrid']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonRow: typeof import('@ionic/vue')['IonRow']
    IonSearchbar: typeof import('@ionic/vue')['IonSearchbar']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    LoginForm: typeof import('./src/components/forms/LoginForm.vue')['default']
    NavBar: typeof import('./src/layouts/components/NavBar.vue')['default']
    RecentMessages: typeof import('./src/components/RecentMessages.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleCurrentChart: typeof import('./src/components/SingleCurrentChart.vue')['default']
    TableApplication: typeof import('./src/components/tables/application/TableApplication.vue')['default']
    TableDeviceProfiles: typeof import('./src/components/tables/deviceProlfiles/TableDeviceProfiles.vue')['default']
    TableGateways: typeof import('./src/components/tables/gateways/TableGateways.vue')['default']
    TableTenants: typeof import('./src/components/tables/tenants/TableTenants.vue')['default']
    TableUsers: typeof import('./src/components/tables/users/TableUsers.vue')['default']
    VoltageChart: typeof import('./src/components/VoltageChart.vue')['default']
  }
}
