# Generated by Django 5.2.4 on 2025-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
