# Generated by Django 5.2.4 on 2025-11-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
