# Generated by Django 5.2.4 on 2026-09-29 16:34

import django.db.models.deletion
import organizations.hasher
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackupCode',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('is_consumed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(db_index=True, max_length=255)),
                ('device_name', models.CharField(default='Dispositivo', max_length=255)),
                ('trust_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UserTwoFactorMethod',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('EMAIL', 'Email'), ('TOTP', 'TOTP Authenticator'), ('BACKUP_CODES', 'Backup Codes')], max_length=20)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'method_type')},
            },
        ),
    ]
