# Generated by Django 5.2.4 on 2026-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userbackupcode_usersession_usertwofactormethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_token_jti',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
