# Generated by Django 5.2.4 on 2025-08-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
