# Generated by Django 5.2.4 on 2025-11-21 17:06

import organizations.hasher
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support/attachments/ticket/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('response', models.BooleanField(default=False)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support/attachments/comment/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Notification', max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportMembership',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('support_agent', 'Support Agent'), ('support_manager', 'Support Manager'), ('technician', 'Technician'), ('other', 'Other')], default='other', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='Medium', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General'), ('account', 'Account'), ('technical', 'Technical'), ('infrastructure', 'Infrastructure'), ('billing', 'Billing'), ('feedback', 'Feedback'), ('other', 'Other')], default='General', max_length=50)),
                ('infrastructure_category', models.CharField(choices=[('devices', 'Devices'), ('gateways', 'Gateways'), ('machines', 'Machines'), ('applications', 'Applications'), ('measurements', 'Measurements'), ('other', 'Other')], default='Other', max_length=50)),
                ('machine_type', models.CharField(blank=True, choices=[('electric', 'Motor Eléctrico'), ('mechanical', 'Motor Mecánico')], max_length=20, null=True)),
                ('electric_machine_subtype', models.CharField(blank=True, choices=[('motor', 'Motor'), ('motobomba', 'Motobomba'), ('motoreductor', 'Motoreductor'), ('ventilador', 'Ventilador'), ('compresor', 'Compresor'), ('vibrador', 'Vibrador'), ('muela', 'Muela'), ('torre_grua', 'Torre Grúa')], max_length=50, null=True)),
                ('mechanical_machine_subtype', models.CharField(blank=True, choices=[('motor_diesel', 'Motor Diésel'), ('motor_gasolina', 'Motor Gasolina'), ('motobomba', 'Motobomba'), ('mixer', 'Mixer'), ('barco', 'Barco'), ('mula', 'Mula'), ('damper', 'Dámper'), ('planta_electrica', 'Planta Eléctrica'), ('compresor', 'Compresor'), ('vibrador', 'Vibrador'), ('compactador', 'Compactador'), ('retroexcavadora', 'Retroexcavadora'), ('niveladora', 'Niveladora'), ('combinada', 'Combinada'), ('tractor', 'Tractor')], max_length=50, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
