# Generated by Django 5.2.4 on 2026-07-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
