# Generated by Django 5.2.4 on 2025-10-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('account', 'Account'), ('technical', 'Technical'), ('infrastructure', 'Infrastructure'), ('billing', 'Billing'), ('feedback', 'Feedback'), ('other', 'Other')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='electric_machine_subtype',
            field=models.CharField(blank=True, choices=[('motor', 'Motor'), ('motobomba', 'Motobomba'), ('motoreductor', 'Motoreductor'), ('ventilador', 'Ventilador'), ('compresor', 'Compresor'), ('vibrador', 'Vibrador'), ('muela', 'Muela'), ('torre_grua', 'Torre Grúa')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='infrastructure_category',
            field=models.CharField(choices=[('devices', 'Devices'), ('gateways', 'Gateways'), ('machines', 'Machines'), ('applications', 'Applications'), ('measurements', 'Measurements'), ('other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='machine_type',
            field=models.CharField(blank=True, choices=[('electric', 'Motor Eléctrico'), ('mechanical', 'Motor Mecánico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='mechanical_machine_subtype',
            field=models.CharField(blank=True, choices=[('motor_diesel', 'Motor Diésel'), ('motor_gasolina', 'Motor Gasolina'), ('motobomba', 'Motobomba'), ('mixer', 'Mixer'), ('barco', 'Barco'), ('mula', 'Mula'), ('damper', 'Dámper'), ('planta_electrica', 'Planta Eléctrica'), ('compresor', 'Compresor'), ('vibrador', 'Vibrador'), ('compactador', 'Compactador'), ('retroexcavadora', 'Retroexcavadora'), ('niveladora', 'Niveladora'), ('combinada', 'Combinada'), ('tractor', 'Tractor')], max_length=50, null=True),
        ),
    ]
