# Generated by Django 5.2.4 on 2026-09-07 20:09

import django.db.models.deletion
import organizations.hasher
from django.conf import settings
from django.db import migrations, models


def backfill_tickets_and_memberships(apps, schema_editor):
    Ticket = apps.get_model("support", "Ticket")
    Tenant = apps.get_model("organizations", "Tenant")
    global_tenant = Tenant.objects.filter(is_global=True).first()
    for ticket in Ticket.objects.filter(tenant__isnull=True):
        if ticket.user and getattr(ticket.user, "tenant", None):
            ticket.tenant = ticket.user.tenant
        elif global_tenant:
            ticket.tenant = global_tenant
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_tenant_unique_global'),
        ('support', '0003_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmembership',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_memberships', to='organizations.tenant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizations.tenant'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organizations.workspace'),
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_diagnostic_passes', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_passes', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_passes', to='support.ticket')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_passes', to='organizations.workspace')),
            ],
        ),
        migrations.RunPython(backfill_tickets_and_memberships, reverse_code=migrations.RunPython.noop),
    ]
