# Generated by Django 5.2.4 on 2025-11-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_ticket_priority_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
