# Generated by Django 5.2.4 on 2025-11-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_ticket_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
