# Generated by Django 5.2.4 on 2025-11-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_comment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
