"""
Django settings for platform_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

import environ
from decouple import config


# ============================================================================
# BASE CONFIGURATION
# ============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DJANGO_DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")


# ============================================================================
# SECURITY SETTINGS
# ============================================================================

SECRET_KEY = env("DJANGO_SECRET_KEY", default="dev")
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["*"])
SERVICE_API_KEY = env("SERVICE_API_KEY", default="default_service_api_key")

# ============================================================================
# APPLICATION DEFINITION
# ============================================================================

INSTALLED_APPS = [
    "django_db_prefix",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "roles",
    "organizations",
    "infrastructure",
    "chirpstack",
    "support",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
    "guardian",
    "auditlog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "platform_backend.urls"

WSGI_APPLICATION = "platform_backend.wsgi.application"


# ============================================================================
# TEMPLATES CONFIGURATION
# ============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("POSTGRES_DB"),
        "USER": env("POSTGRES_USER"),
        "PASSWORD": env("POSTGRES_PASSWORD"),
        "HOST": env("POSTGRES_HOST"),
        "PORT": env("POSTGRES_PORT"),
    }
}

DB_PREFIX = env("DB_PREFIX")
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================================
# AUTHENTICATION AND AUTHORIZATION
# ============================================================================

AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

GUARDIAN_RAISE_403 = True

# ============================================================================
# INTERNATIONALIZATION
# ============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ============================================================================
# STATIC AND MEDIA FILES
# ============================================================================

STATIC_URL = "static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"


# ============================================================================
# CORS AND CSRF SETTINGS
# ============================================================================

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=True, cast=bool)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:3000",
    cast=lambda v: [s.strip() for s in v.split(",")],
)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_SAMESITE = config("CSRF_COOKIE_SAMESITE", default="Lax", cast=str)
CSRF_COOKIE_HTTPONLY = False  # Allow JS to read CSRF token if needed

SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)
COOKIE_SECURE = config("COOKIE_SECURE", default=False, cast=bool)


# ============================================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# ============================================================================
# JWT AUTHENTICATION SETTINGS
# ============================================================================

ACCESS_TOKEN_DURATION = env.int("ACCESS_TOKEN_DURATION", default=5)
REFRESH_TOKEN_DURATION = env.int("REFRESH_TOKEN_DURATION", default=30)

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=ACCESS_TOKEN_DURATION),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=REFRESH_TOKEN_DURATION),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
    "TOKEN_OBTAIN_SERIALIZER": "users.serializers.CustomTokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "users.serializers.CustomTokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

REFRESH_COOKIE_NAME = env("REFRESH_COOKIE_NAME", default="refresh_token")
REFRESH_COOKIE_PATH = env("REFRESH_COOKIE_PATH", default="/")


# ============================================================================
# API DOCUMENTATION SETTINGS
# ============================================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "Monitor Atlas API V1.1",
    "DESCRIPTION": "API para la plataforma de monitorización Monitor Atlas - Powered by Weedo",
    "VERSION": "1.1.0",
    "SCHEMA_PATH_PREFIX": "/api/v1/",
}


# ============================================================================
# GOOGLE OAUTH CONFIGURATION
# ============================================================================

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID", default=None)
GOOGLE_SECRET = env("GOOGLE_SECRET", default=None)
GOOGLE_ISS = env("GOOGLE_ISS", default=None)


# ============================================================================
# EMAIL CONFIGURATION
# ============================================================================

MAILGUN_API_KEY = env("MAILGUN_API_KEY", default=None)
MAILGUN_DOMAIN = env("MAILGUN_DOMAIN", default=None)
MAILGUN_FROM = env("MAILGUN_FROM", default="no-reply@yourdomain.com")


# ============================================================================
# CHIRPSTACK INTEGRATION
# ============================================================================

CHIRPSTACK_BASE_URL = env("CHIRPSTACK_BASE_URL", default=None)
CHIRPSTACK_JWT_TOKEN = env("CHIRPSTACK_JWT_TOKEN", default=None)


# ============================================================================
# EXTERNAL SERVICES CONFIGURATION
# ============================================================================

APP_URL = env("APP_URL", default="http://localhost:5173")
MTR_LOGO_URL = env("MTR_LOGO_URL", default="https://placehold.co/500x200")

HERMES_WS_URL = env("HERMES_WS_URL", default="ws://localhost:5000")
HERMES_API_URL = env("HERMES_API_URL", default="http://localhost:5000")
WS_SECRET = env("WS_SECRET", default="dummy32characterslong!!")


# ============================================================================
# LOGGING (Loguru)
# ============================================================================

from loguru import logger

LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

logger.add(
    LOGS_DIR / "system.log",
    rotation="5 MB",
    retention="7 days",
    level="INFO",
    format="{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}",
)
