# Generated by Django 5.2.4 on 2025-11-21 17:06

import django.db.models.deletion
import organizations.hasher
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('can_have_gateways', models.BooleanField(default=False)),
                ('max_device_count', models.IntegerField(default=0)),
                ('max_gateway_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('cs_tenant_id', models.CharField(blank=True, max_length=36, null=True)),
                ('name', models.CharField(max_length=90)),
                ('img', models.FileField(blank=True, null=True, upload_to='tenant_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('is_global', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('img', models.FileField(blank=True, null=True, upload_to='workspace_images/')),
                ('description', models.CharField(max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
    ]
