# Generated by Django 5.2.4 on 2025-10-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='group',
        ),
    ]
