# Generated by Django 5.2.4 on 2025-08-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='cs_tenant_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
