# Generated by Django 5.2.4 on 2025-08-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_tenant_cs_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
