# Generated by Django 5.2.4 on 2026-09-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_tenant_unique_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='security_level',
            field=models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, default='MEDIUM', max_length=10),
        ),
    ]
