# Generated by Django 5.2.4 on 2025-11-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_tenant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='tenant_images/'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='workspace_images/'),
        ),
    ]
