# Generated by Django 5.2.4 on 2025-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_tenant_img_alter_workspace_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
