services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file: .env.prod
    volumes:
      - ./app:/app/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis-hermes
    healthcheck:
      # Check the FastAPI health endpoint; adjust path if your app uses a different one
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:5000/health || wget --spider --quiet http://localhost:5000/healthz || (nc -z localhost 5000 || exit 1)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - chirp-django-net

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    env_file: .env.prod
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.adminCommand(\"ping\")' --quiet || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - chirp-django-net

  redis-hermes:
    image: redis:7.2-alpine
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env.prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      # Use redis-cli PING; include password if REDIS_PASSWORD is set
      test: ["CMD-SHELL", "if [ -n \"${REDIS_PASSWORD}\" ]; then redis-cli -a \"${REDIS_PASSWORD}\" PING || exit 1; else redis-cli PING || exit 1; fi"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - chirp-django-net

volumes:
  mongo_data:
  redis_data:

networks:
  chirp-django-net:
    external: true
