services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file: .env
    volumes:
      - ./app:/app/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - chirp-django-net

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - chirp-django-net

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - chirp-django-net
      
volumes:
  mongo_data:
  redis_data:
networks:
  chirp-django-net:
    external: true  