# Generated by Django 5.2.4 on 2025-11-21 17:06

import django.db.models.deletion
import organizations.hasher
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#bfbfbf', max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.role')),
            ],
        ),
    ]
