# Generated by Django 5.2.4 on 2025-10-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#bfbfbf', max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
            ],
            options={
                'permissions': (('manage_roles', 'Can manage roles'), ('assign_roles', 'Can assign roles to users')),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.role')),
            ],
            options={
                'permissions': (('manage_memberships', 'Can manage workspace memberships'),),
            },
        ),
    ]
