# Generated by Django 5.2.4 on 2026-10-05 20:42

import django.db.models.deletion
import organizations.hasher
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Generated backup archive filename (e.g., backup_YYYYMMDD_HHMMSS.sql.gz)', max_length=255)),
                ('s3_key', models.CharField(help_text='Cloudflare R2 object key (e.g., backups/postgresql/YYYY/MM/backup_YYYYMMDD_HHMMSS.sql.gz)', max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Exact size of the compressed archive in bytes')),
                ('checksum_sha256', models.CharField(blank=True, default='', help_text='64-character lowercase SHA-256 hex digest of the archive', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('trigger_type', models.CharField(choices=[('MANUAL_CLI', 'Manual CLI'), ('MANUAL_API', 'Manual API'), ('AUTOMATED_SCHEDULE', 'Automated Schedule'), ('SCHEDULED_CELERY', 'Scheduled Celery')], db_index=True, default='MANUAL_CLI', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
    ]
