# Generated by Django 5.2.4 on 2025-08-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0002_alter_apiuser_cs_user_id_alter_apiuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceprofile',
            name='vendor',
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='supports_otaa',
            field=models.BooleanField(default=False),
        ),
    ]
