# Generated by Django 5.2.4 on 2025-08-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0003_remove_deviceprofile_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='cs_device_profile_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
