# Generated by Django 5.2.4 on 2025-08-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0004_alter_deviceprofile_cs_device_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='payload_codec_script',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
