# Generated by Django 5.2.4 on 2025-09-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0005_deviceprofile_payload_codec_script'),
        ('organizations', '0003_alter_tenant_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deviceprofile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='deviceprofiletemplate',
            name='tenant',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace'),
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace'),
        ),
        migrations.AddField(
            model_name='deviceprofiletemplate',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace'),
        ),
    ]
