# Generated by Django 5.2.4 on 2025-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0006_remove_apiuser_tenant_remove_deviceprofile_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='deviceprofiletemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
