# Generated by Django 5.2.4 on 2025-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0007_alter_deviceprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceprofile',
            name='payload_codec_script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
