# Generated by Django 5.2.4 on 2025-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0008_alter_deviceprofile_payload_codec_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceprofile',
            name='adr_algorithm_id',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='flush_queue_on_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deviceprofile',
            name='uplink_interval',
            field=models.IntegerField(default=3000),
        ),
    ]
