# Generated by Django 5.2.4 on 2025-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0009_deviceprofile_adr_algorithm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='cs_user_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceprofile',
            name='cs_device_profile_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
