# Generated by Django 5.2.4 on 2025-08-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionkey',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.subscription'),
        ),
        migrations.AlterField(
            model_name='permissionkey',
            name='scope',
            field=models.CharField(choices=[('device', 'Device'), ('machine', 'Machine'), ('application', 'Application'), ('user', 'User'), ('role', 'Role'), ('workspace', 'Workspace'), ('tenant', 'Tenant'), ('location', 'Location'), ('gateway', 'Gateway'), ('device_profile', 'DeviceProfile'), ('device_profile_template', 'DeviceProfileTemplate'), ('api_user', 'ApiUser'), ('tenant_user', 'TenantUser'), ('type', 'Type'), ('subscription', 'Subscription')], max_length=30),
        ),
    ]
