# Generated by Django 5.2.4 on 2025-08-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissionkey',
            name='scope',
            field=models.CharField(choices=[('node', 'Node'), ('machine', 'Machine'), ('service', 'Service'), ('user', 'User'), ('role', 'Role'), ('workspace', 'Workspace'), ('organization', 'Organization'), ('region', 'Region'), ('permission_key', 'PermissionKey')], max_length=30),
        ),
    ]
