# Generated by Django 5.2.4 on 2025-08-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_node_name_alter_service_name'),
        ('roles', '0003_role_is_admin_alter_permissionkey_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionkey',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.gateway'),
        ),
        migrations.AlterField(
            model_name='permissionkey',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='permissionkey',
            name='scope',
            field=models.CharField(choices=[('node', 'Node'), ('machine', 'Machine'), ('service', 'Service'), ('user', 'User'), ('role', 'Role'), ('workspace', 'Workspace'), ('organization', 'Organization'), ('region', 'Region'), ('permission_key', 'PermissionKey'), ('gateway', 'Gateway')], max_length=30),
        ),
    ]
