# Generated by Django 5.2.4 on 2025-08-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_permissionkey_gateway_alter_permissionkey_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionkey',
            name='scope',
            field=models.CharField(choices=[('node', 'Node'), ('machine', 'Machine'), ('service', 'Service'), ('user', 'User'), ('role', 'Role'), ('workspace', 'Workspace'), ('organization', 'Organization'), ('region', 'Region'), ('permission_key', 'PermissionKey'), ('gateway', 'Gateway'), ('role_permission', 'RolePermission')], max_length=30),
        ),
    ]
