# Generated by Django 5.2.4 on 2025-08-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_permissionkey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
