# Generated by Django 5.2.4 on 2025-08-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_user_id', models.CharField(max_length=36)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('is_tenant_admin', models.BooleanField(default=False)),
                ('is_tenant_device_admin', models.BooleanField(default=False)),
                ('is_tenant_gateway_admin', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default='PENDING', max_length=30)),
                ('sync_error', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_device_profile_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=30)),
                ('vendor', models.CharField(default='EMASA', max_length=30)),
                ('mac_version', models.CharField(default='LORAWAN_1_0_3', max_length=30)),
                ('reg_param_revision', models.CharField(default='A', max_length=30)),
                ('abp_rx1_delay', models.IntegerField()),
                ('abp_rx1_dr_offset', models.IntegerField()),
                ('abp_rx2_dr', models.IntegerField()),
                ('abp_rx2_freq', models.IntegerField()),
                ('supports_class_b', models.BooleanField(default=False)),
                ('supports_class_c', models.BooleanField(default=False)),
                ('payload_codec_runtime', models.CharField(default='JS', max_length=30)),
                ('is_rlay', models.BooleanField(default=False)),
                ('is_rlay_ed', models.BooleanField(default=False)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default='PENDING', max_length=30)),
                ('sync_error', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProfileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=30)),
                ('vendor', models.CharField(default='EMASA', max_length=30)),
                ('mac_version', models.CharField(default='LORAWAN_1_0_3', max_length=30)),
                ('reg_param_revision', models.CharField(default='A', max_length=30)),
                ('abp_rx1_delay', models.IntegerField()),
                ('abp_rx1_dr_offset', models.IntegerField()),
                ('abp_rx2_dr', models.IntegerField()),
                ('abp_rx2_freq', models.IntegerField()),
                ('supports_class_b', models.BooleanField(default=False)),
                ('supports_class_c', models.BooleanField(default=False)),
                ('payload_codec_runtime', models.CharField(default='JS', max_length=30)),
                ('is_rlay', models.BooleanField(default=False)),
                ('is_rlay_ed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
    ]
