# Generated by Django 5.2.4 on 2025-08-21 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProfileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30)),
                ('mac_version', models.CharField(max_length=30)),
                ('reg_param_revision', models.CharField(default='A', max_length=30)),
                ('abp_rx1_delay', models.IntegerField()),
                ('abp_rx1_dr_offset', models.IntegerField()),
                ('abp_rx2_dr', models.IntegerField()),
                ('abp_rx2_freq', models.IntegerField()),
                ('adr_algorithm', models.CharField(max_length=30)),
                ('firmware', models.CharField(max_length=255)),
                ('flush_queue_on_activate', models.BooleanField(default=False)),
                ('supports_otaa', models.BooleanField(default=False)),
                ('supports_class_b', models.BooleanField(default=False)),
                ('supports_class_c', models.BooleanField(default=False)),
                ('payload_codec_runtime', models.CharField(default='JS', max_length=30)),
                ('payload_codec_script', models.CharField(max_length=255)),
                ('uplink_interval', models.IntegerField(default=18)),
                ('auto_detect_measurements', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=30)),
                ('vendor', models.CharField(default='EMASA', max_length=30)),
                ('mac_version', models.CharField(default='LORAWAN_1_0_3', max_length=30)),
                ('reg_param_revision', models.CharField(default='A', max_length=30)),
                ('abp_rx1_delay', models.IntegerField()),
                ('abp_rx1_dr_offset', models.IntegerField()),
                ('abp_rx2_dr', models.IntegerField()),
                ('abp_rx2_freq', models.IntegerField()),
                ('supports_class_b', models.BooleanField(default=False)),
                ('supports_class_c', models.BooleanField(default=False)),
                ('payload_codec_runtime', models.CharField(default='JS', max_length=30)),
                ('is_rlay', models.BooleanField(default=False)),
                ('is_rlay_ed', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_device_admin', models.BooleanField(default=False)),
                ('is_gateway_admin', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chirpstack.apiuser')),
            ],
        ),
    ]
