# Generated by Django 5.2.4 on 2025-08-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirpstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='cs_user_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
