# Generated by Django 5.2.4 on 2025-08-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chirpstack', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('accuracy', models.FloatField()),
                ('altitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('GPS', 'GPS'), ('CONFIG', 'Manually configured'), ('GEO_RESOLVER_TDOA', 'Geo resolver (TDOA)'), ('GEO_RESOLVER_RSSI', 'Geo resolver (RSSI)'), ('GEO_RESOLVER_GNSS', 'Geo resolver (GNSS)'), ('GEO_RESOLVER_WIFI', 'Geo resolver (WiFi)')], default='UNKNOWN')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_application_id', models.CharField(help_text='Application ID (Chirpstack)', max_length=36)),
                ('name', models.CharField(max_length=30)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
                ('device_type', models.ForeignKey(help_text='You can classify devices by type and set a custom icon', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.type')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_gateway_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('stats_interval', models.IntegerField()),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.location')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(help_text='Device EUI (Chirpstack)', max_length=16)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='Application (Chirpstack)', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.application')),
                ('device_profile', models.ForeignKey(help_text='Device profile (Chirpstack)', on_delete=django.db.models.deletion.CASCADE, to='chirpstack.deviceprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.machine')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.type')),
            ],
        ),
    ]
