# Generated by Django 5.2.4 on 2025-10-30 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chirpstack', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afcntdown', models.IntegerField()),
                ('app_s_key', models.CharField(help_text='Application session key (Chirpstack)', max_length=32)),
                ('dev_addr', models.CharField(help_text='Device address (Chirpstack)', max_length=8)),
                ('f_cnt_up', models.IntegerField()),
                ('f_nwk_s_int_key', models.CharField(help_text='Network session key (Chirpstack)', max_length=32)),
                ('n_f_cnt_down', models.IntegerField()),
                ('nwk_s_enc_key', models.CharField(help_text='Network session key (Chirpstack)', max_length=32)),
                ('s_nwk_s_int_key', models.CharField(default='', help_text='Network session key (Chirpstack)', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unknown', max_length=255, null=True)),
                ('accuracy', models.FloatField(blank=True, default=0.0, null=True)),
                ('altitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('source', models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('GPS', 'GPS'), ('CONFIG', 'Manually configured'), ('GEO_RESOLVER_TDOA', 'Geo resolver (TDOA)'), ('GEO_RESOLVER_RSSI', 'Geo resolver (RSSI)'), ('GEO_RESOLVER_GNSS', 'Geo resolver (GNSS)'), ('GEO_RESOLVER_WIFI', 'Geo resolver (WiFi)')], default='UNKNOWN', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_application_id', models.CharField(blank=True, help_text='Application ID (Chirpstack)', max_length=36, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
                ('device_type', models.ForeignKey(help_text='You can classify devices by type and set a custom icon', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.type')),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_gateway_id', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('stats_interval', models.IntegerField(default=30)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.location')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(help_text='Device EUI (Chirpstack)', max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_disabled', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('ERROR', 'Error')], default=False, max_length=30)),
                ('sync_error', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('enabled_activation', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.activation')),
                ('application', models.ForeignKey(help_text='Application (Chirpstack)', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.application')),
                ('device_profile', models.ForeignKey(help_text='Device profile (Chirpstack)', on_delete=django.db.models.deletion.CASCADE, to='chirpstack.deviceprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.workspace')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.machine')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.type')),
            ],
        ),
    ]
