# Generated by Django 5.2.4 on 2025-11-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='machine_icons/'),
        ),
        migrations.AlterField(
            model_name='type',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='type_icons/'),
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('threshold', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.device')),
            ],
        ),
    ]
