# Generated by Django 5.2.4 on 2025-11-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.activation'),
        ),
        migrations.AlterField(
            model_name='device',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.machine'),
        ),
    ]
