# Generated by Django 5.2.4 on 2025-08-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afcntdown', models.IntegerField()),
                ('app_s_key', models.CharField(help_text='Application session key (Chirpstack)', max_length=32)),
                ('dev_addr', models.CharField(help_text='Device address (Chirpstack)', max_length=8)),
                ('f_cnt_up', models.IntegerField()),
                ('f_nwk_s_int_key', models.CharField(help_text='Network session key (Chirpstack)', max_length=32)),
                ('n_f_cnt_down', models.IntegerField()),
                ('nwk_s_enc_key', models.CharField(help_text='Network session key (Chirpstack)', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='enabled_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='cs_gateway_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='location',
            name='accuracy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='altitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='source',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Unknown'), ('GPS', 'GPS'), ('CONFIG', 'Manually configured'), ('GEO_RESOLVER_TDOA', 'Geo resolver (TDOA)'), ('GEO_RESOLVER_RSSI', 'Geo resolver (RSSI)'), ('GEO_RESOLVER_GNSS', 'Geo resolver (GNSS)'), ('GEO_RESOLVER_WIFI', 'Geo resolver (WiFi)')], default='UNKNOWN', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='activation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.activation'),
        ),
    ]
