# Generated by Django 5.2.4 on 2025-11-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_machine_img_alter_type_img_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='measurement_icons/'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
