# Generated by Django 5.2.4 on 2025-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_activation_device_enabled_activation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='stats_interval',
            field=models.IntegerField(default=30),
        ),
    ]
