# Generated by Django 5.2.4 on 2025-12-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_device_activation_alter_device_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
