# Generated by Django 5.2.4 on 2025-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_gateway_stats_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cs_application_id',
            field=models.CharField(blank=True, help_text='Application ID (Chirpstack)', max_length=36, null=True),
        ),
    ]
