# Generated by Django 5.2.4 on 2026-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_alter_measurements_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='img',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
