# Generated by Django 5.2.4 on 2026-07-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_type_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
