# Generated by Django 5.2.4 on 2026-09-08 15:53

import django.db.models.deletion
import organizations.hasher
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_measurements_label'),
        ('organizations', '0002_tenant_unique_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='require_consent',
            field=models.BooleanField(default=True, help_text='Indicates whether collecting this measurement for model training requires explicit tenant consent'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.type'),
        ),
        migrations.CreateModel(
            name='DeviceConsent',
            fields=[
                ('id', models.CharField(default=organizations.hasher.generate_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('SUPERSEDED', 'Superseded')], db_index=True, default='ACTIVE', max_length=20)),
                ('terms_version', models.CharField(default='v1.0', max_length=50)),
                ('device_signature', models.CharField(max_length=64)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='', null=True)),
                ('consented_measurements', models.ManyToManyField(blank=True, related_name='device_consents', to='infrastructure.measurements')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='infrastructure.device')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_device_consents', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_device_consents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_consents', to='organizations.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_consents', to='organizations.workspace')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('device',), name='unique_active_device_consent')],
            },
        ),
    ]
