# Generated by Django 5.2.4 on 2025-09-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_device_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
