# Generated by Django 5.2.4 on 2025-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_alter_gateway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
    ]
