# Generated by Django 5.2.4 on 2025-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_alter_application_name_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='s_nwk_s_int_key',
            field=models.CharField(default='', help_text='Network session key (Chirpstack)', max_length=32),
        ),
    ]
