# Generated by Django 5.2.4 on 2025-09-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_activation_s_nwk_s_int_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='cs_gateway_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
