# Generated by Django 5.2.4 on 2025-10-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_alter_gateway_cs_gateway_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='dev_eui',
            field=models.CharField(help_text='Device EUI (Chirpstack)', max_length=16, unique=True),
        ),
    ]
