# Generated by Django 5.2.4 on 2025-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_alter_device_dev_eui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cs_application_id',
            field=models.CharField(blank=True, help_text='Application ID (Chirpstack)', max_length=36, null=True, unique=True),
        ),
    ]
