// Consolidated icon system - All icons in one file
import {
  // Action icons
  cube,
  eyeOutline,
  eyeOffOutline,
  refreshOutline,
  addOutline,
  createOutline,
  trashOutline,
  downloadOutline,
  arrowUpOutline,
  copyOutline,
  saveOutline,
  printOutline,
  shareOutline,
  playOutline,
  pauseOutline,
  stopOutline,
  keyOutline,
  logOutOutline,
  shieldOutline,

  // Communication icons
  mailOutline,
  chatbubbleOutline,
  callOutline,
  videocamOutline,
  heartOutline,
  thumbsUpOutline,
  thumbsDownOutline,
  starOutline,
  personOutline,
  peopleOutline,
  notificationsOutline,
  personAddOutline,

  // Data icons
  documentOutline,
  folderOutline,
  folderOpenOutline,
  archiveOutline,
  cloudDownloadOutline,
  cloudOutline,
  attachOutline,
  linkOutline,
  codeSlashOutline,
  terminalOutline,
  libraryOutline,
  bookmarkOutline,
  analyticsOutline,

  // Hardware icons
  hardwareChipOutline,
  phonePortraitOutline,
  serverOutline,
  wifiOutline,
  bluetoothOutline,
  desktopOutline,
  laptopOutline,
  tabletPortraitOutline,
  cameraOutline,
  micOutline,
  batteryFullOutline,
  batteryHalfOutline,

  // Location icons
  locationOutline,
  mapOutline,
  navigateOutline,
  compassOutline,
  globeOutline,
  homeOutline,
  businessOutline,
  carOutline,
  trainOutline,
  airplaneOutline,

  // Navigation icons
  chevronUpOutline,
  chevronDownOutline,
  chevronBackOutline,
  chevronForwardOutline,
  arrowBackOutline,
  arrowForwardOutline,
  caretUpOutline,
  caretDownOutline,
  arrowUpCircleOutline,
  arrowDownCircleOutline,

  // Status icons
  alertCircleOutline,
  checkmarkCircleOutline,
  warningOutline,
  informationCircleOutline,
  closeCircleOutline,
  helpCircleOutline,
  helpBuoyOutline,
  timeOutline,
  powerOutline,
  flashOutline,
  lockClosedOutline,
  lockOpenOutline,

  // UI icons
  searchOutline,
  filterOutline,
  menuOutline,
  settingsOutline,
  settings,
  optionsOutline,
  listOutline,
  gridOutline,
  appsOutline,
  apps,
  layersOutline,
  swapHorizontalOutline,
  swapVerticalOutline,
  resizeOutline,
  close,
  ellipseOutline,
} from 'ionicons/icons'

// Custom SVG icon
import plugOutline from '@assets/icons/plug.svg'
import enginesOutline from '@assets/icons/engines.svg'
import packageOutline from '@assets/icons/package.svg'
import deviceCard from '@assets/icons/device_card.svg'

export const icons = {
  // Action icons
  'eye': eyeOutline,
  'eyeOff': eyeOffOutline,
  'refresh': refreshOutline,
  'add': addOutline,
  'edit': createOutline,
  'delete': trashOutline,
  'download': downloadOutline,
  'upload': arrowUpOutline,
  'copy': copyOutline,
  'save': saveOutline,
  'print': printOutline,
  'share': shareOutline,
  'play': playOutline,
  'pause': pauseOutline,
  'stop': stopOutline,
  'key': keyOutline,
  'logOut': logOutOutline,
  'shield': shieldOutline,
  'cube': cube,

  // Communication icons
  'mail': mailOutline,
  'chat': chatbubbleOutline,
  'call': callOutline,
  'video-call': videocamOutline,
  'heart': heartOutline,
  'thumbs-up': thumbsUpOutline,
  'thumbs-down': thumbsDownOutline,
  'star': starOutline,
  'person': personOutline,
  'people': peopleOutline,
  'notifications': notificationsOutline,

  // Data icons
  'document': documentOutline,
  'folder': folderOutline,
  'folder-open': folderOpenOutline,
  'archive': archiveOutline,
  'cloud-download': cloudDownloadOutline,
  'cloud-upload': cloudOutline,
  'attach': attachOutline,
  'link': linkOutline,
  'code': codeSlashOutline,
  'terminal': terminalOutline,
  'library': libraryOutline,
  'bookmark': bookmarkOutline,
  'analytics': analyticsOutline,
  'package': packageOutline,

  // Hardware icons
  'hardwareChip': hardwareChipOutline,
  'phonePortrait': phonePortraitOutline,
  'server': serverOutline,
  'cloud': cloudOutline,
  'wifi': wifiOutline,
  'bluetooth': bluetoothOutline,
  'desktop': desktopOutline,
  'laptop': laptopOutline,
  'tablet': tabletPortraitOutline,
  'camera': cameraOutline,
  'video': videocamOutline,
  'microphone': micOutline,
  'batteryFull': batteryFullOutline,
  'batteryHalf': batteryHalfOutline,
  'plug': plugOutline,
  'engines': enginesOutline,
  'deviceCard': deviceCard,

  // Location icons
  'location': locationOutline,
  'map': mapOutline,
  'navigate': navigateOutline,
  'compass': compassOutline,
  'globe': globeOutline,
  'home': homeOutline,
  'business': businessOutline,
  'car': carOutline,
  'train': trainOutline,
  'airplane': airplaneOutline,
  'building': businessOutline,

  // Navigation icons
  'chevronUp': chevronUpOutline,
  'chevronDown': chevronDownOutline,
  'chevronBack': chevronBackOutline,
  'chevronForward': chevronForwardOutline,
  'arrowBack': arrowBackOutline,
  'arrowForward': arrowForwardOutline,
  'caretUp': caretUpOutline,
  'caretDown': caretDownOutline,
  'arrowUpCircle': arrowUpCircleOutline,
  'arrowDownCircle': arrowDownCircleOutline,

  // Status icons
  'alert': alertCircleOutline,
  'alertCircle': alertCircleOutline,
  'success': checkmarkCircleOutline,
  'warning': warningOutline,
  'info': informationCircleOutline,
  'error': closeCircleOutline,
  'help': helpCircleOutline,
  'helpBuoy': helpBuoyOutline,
  'time': timeOutline,
  'power': powerOutline,
  'lock_closed': lockClosedOutline,
  'lock-open': lockOpenOutline,
  'flash': flashOutline,

  // UI icons
  'search': searchOutline,
  'filter': filterOutline,
  'menu': menuOutline,
  'settings': settingsOutline,
  'options': optionsOutline,
  'list': listOutline,
  'grid': gridOutline,
  'apps': appsOutline,
  'layers': layersOutline,
  'swap-horizontal': swapHorizontalOutline,
  'swap-vertical': swapVerticalOutline,
  'resize': resizeOutline,
  'close': close,
  'ellipse': ellipseOutline,
  'person_add': personAddOutline,
}

// Helper function to get icon by name
export const getIcon = (name) => {
  return icons[name] || null
}