services:
  db:
    image: postgres:16
    container_name: postgres_backend
    restart: unless-stopped
    env_file: .env.db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - chirp-django-net

  web:
    build: .
    container_name: django_backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - chirp-django-net

volumes:
  postgres_data:

networks:
  chirp-django-net:
    external: true
