version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres_backend
    restart: unless-stopped
    env_file: .env.db.prod
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-appdb} -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - chirp-django-net

  web:
    build: .
    container_name: django_backend
    restart: unless-stopped
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      # Try the Django health endpoint, fallback to checking that the port is open
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8000/health || wget --spider --quiet http://localhost:8000/healthz || (nc -z localhost 8000 || exit 1)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - chirp-django-net

volumes:
  postgres_data:

networks:
  chirp-django-net:
    external: true
